# Generated by Django 3.2.12 on 2022-03-01 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Goal Name')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Name')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='organization.department')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicator', to='organization.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodicity Name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='State Name')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit Name')),
                ('type', models.CharField(choices=[('Academic Unit', 'Academic Unit'), ('Standard Unit', 'Standard Unit')], default='Standard Unit', max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit Value')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scheme Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Scheme Description')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='organization.district')),
                ('indicator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='organization.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('latitude', models.CharField(max_length=255, verbose_name='Location Latitude')),
                ('longitude', models.CharField(max_length=255, verbose_name='Location Longitude')),
                ('pincode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Pincode')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location Description')),
                ('district', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='organization.district')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('baseline', 'baseline'), ('progress', 'progress'), ('target', 'target')], default='baseline', max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Value')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicatorvalue', to='organization.district')),
                ('indicator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicatorvalue', to='organization.indicator')),
            ],
        ),
        migrations.AddField(
            model_name='indicator',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicator', to='organization.periodicity'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indicator', to='organization.unit'),
        ),
        migrations.AddField(
            model_name='goal',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='organization.state'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='organization.state'),
        ),
        migrations.AddField(
            model_name='department',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='organization.state'),
        ),
        migrations.AddField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
