# Generated by Django 3.2.12 on 2022-07-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Score')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='score', to='organization.goal')),
            ],
        ),
    ]
