# Generated by Django 3.2.12 on 2022-07-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='organization.indicator'),
        ),
    ]
