# Generated by Django 3.2.12 on 2022-07-15 06:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_goal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
