# Generated by Django 3.2.12 on 2022-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_goal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='type',
            field=models.CharField(blank=True, default='DIF', max_length=255, null=True, verbose_name='Indicator Type'),
        ),
    ]
