# Generated by Django 3.2.12 on 2022-07-15 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_indicator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='score',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='score',
            name='vetted_by_department',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='vetted_by_officer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
