# Generated by Django 3.2.12 on 2022-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20220715_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorvalue',
            name='mid_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Value'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='short_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Value'),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
