# Generated by Django 3.2.12 on 2022-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20220718_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='indicatorvalue',
            name='value_type',
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='baseline_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Baseline Value'),
        ),
        migrations.AddField(
            model_name='indicatorvalue',
            name='progress_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Progress Value'),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='mid_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator mid target Value'),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='short_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator short target Value'),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator target Value'),
        ),
    ]
