# Generated by Django 3.2.12 on 2022-07-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_score_vetted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='vetted_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='vetted by name'),
        ),
    ]
