# Generated by Django 3.2.12 on 2022-08-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_score_vetted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='organization.goal'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='organization.periodicity'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='organization.unit'),
        ),
        migrations.AlterField(
            model_name='score',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='organization.goal'),
        ),
    ]
