# Generated by Django 3.2.12 on 2022-08-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20220817_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='indicator_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Score'),
        ),
    ]
