# Generated by Django 3.2.12 on 2022-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='sno',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sno'),
        ),
    ]
