# Generated by Django 3.2.12 on 2022-08-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_goal_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='sno',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Goal SNO'),
        ),
    ]
