# Generated by Django 3.2.12 on 2022-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20220912_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='year',
            field=models.CharField(blank=True, default='2021', max_length=255, null=True, verbose_name='Indicator Year'),
        ),
    ]
