# Generated by Django 3.2.12 on 2022-09-13 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_indicator_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='New Score')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('indicator_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Score')),
                ('year', models.CharField(max_length=255, verbose_name='Score Year')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('vetted_by_department', models.BooleanField(blank=True, default=False, null=True)),
                ('vetted_by_officer', models.BooleanField(blank=True, default=False, null=True)),
                ('vetted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='vetted by name')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscores', to='organization.goal')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newscores', to='organization.indicator')),
            ],
        ),
    ]
