# Generated by Django 3.2.12 on 2022-09-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_newscores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscores',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='newscores',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
