# Generated by Django 3.2.12 on 2022-09-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20220913_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscores',
            old_name='approved_by',
            new_name='action_by',
        ),
        migrations.RenameField(
            model_name='newscores',
            old_name='approved_at',
            new_name='action_time',
        ),
    ]
