# Generated by Django 3.2.12 on 2022-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_auto_20220913_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscores',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reject Reason'),
        ),
    ]
