# Generated by Django 3.2.12 on 2022-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_newscores_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicity',
            name='no_of_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodicity Days'),
        ),
    ]
