# Generated by Django 3.2.12 on 2022-09-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_periodicity_no_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='district',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='indicator',
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Scheme Comment'),
        ),
    ]
