# Generated by Django 3.2.12 on 2022-09-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_indicator_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscores',
            name='indicator_value',
        ),
        migrations.RemoveField(
            model_name='newscores',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newscores',
            name='value',
        ),
        migrations.RemoveField(
            model_name='newscores',
            name='year',
        ),
        migrations.AddField(
            model_name='newscores',
            name='denominator_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Denominator Score'),
        ),
        migrations.AddField(
            model_name='newscores',
            name='numerator_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numerator Score'),
        ),
        migrations.AlterField(
            model_name='newscores',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type'),
        ),
    ]
