# Generated by Django 3.2.12 on 2022-09-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20220913_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscores',
            name='created_by',
            field=models.CharField(blank=True, default='user', max_length=255, null=True),
        ),
    ]
