# Generated by Django 3.2.12 on 2022-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20220914_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='denominator_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Denominator Label'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='numerator_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Numerator Label'),
        ),
    ]
