# Generated by Django 3.2.12 on 2022-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_auto_20220914_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicator Comment'),
        ),
    ]
