# Generated by Django 3.2.12 on 2022-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.CharField(choices=[('Aspirant', 'Aspirant'), ('Performer', 'Performer'), ('Front Runner', 'Front Runner'), ('Achiever', 'Achiever'), ('No Target', 'No Target')], default='Aspirant', max_length=255),
        ),
    ]
