# Generated by Django 3.2.12 on 2022-12-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_indicator_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='category',
        ),
        migrations.AddField(
            model_name='newscores',
            name='category',
            field=models.CharField(choices=[('Aspirant', 'Aspirant'), ('Performer', 'Performer'), ('Front Runner', 'Front Runner'), ('Achiever', 'Achiever'), ('No Target', 'No Target')], default='Aspirant', max_length=255),
        ),
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('Aspirant', 'Aspirant'), ('Performer', 'Performer'), ('Front Runner', 'Front Runner'), ('Achiever', 'Achiever'), ('No Target', 'No Target')], default='Aspirant', max_length=255),
        ),
    ]
