# Generated by Django 3.2.12 on 2023-05-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_auto_20221215_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Scheme Name'),
        ),
    ]
