# Generated by Django 3.2.12 on 2024-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_alter_goal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscores',
            name='calculated_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calculated Score'),
        ),
    ]
