# Generated by Django 3.2.12 on 2024-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0042_newscores_calculated_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscores',
            old_name='calculated_value',
            new_name='score_value',
        ),
        migrations.AddField(
            model_name='newscores',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Year'),
        ),
    ]
