# Generated by Django 3.2.12 on 2024-07-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_auto_20240715_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscores',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
