# Generated by Django 3.2.12 on 2024-07-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0044_newscores_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscores',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newscores', to='organization.score'),
        ),
    ]
