const data = [
  {
    roles: [
      "system_administrator",
      "superadmin",
      "general_user",
      "data_entry_operator",
      "state_data_creator",
      "district_data_creator",
      "state_data_approver",
      "district_data_approver",
      "cmo",
      "cso",
      "development_commissioner",
    ],
    id: "DashMain",
    icon: "iconsminds-dashboard",
    label: "Dashboard",
    to: "/app/sdg/dashboard",
  },
  // {
  //   roles: [
  //     "system_administrator",
  //     "superadmin",
  //     "general_user",
  //     "data_entry_operator",
  //     "state_data_creator",
  //     "district_data_creator",
  //     "state_data_approver",
  //     "district_data_approver",
  //     "cmo",
  //     "cso",
  //     "development_commissioner",
  //   ],
  //   id: "protype",
  //   icon: "iconsminds-big-data",
  //   label: "Protype",
  //   to: "/app/protype/",
  //   subs: [
  //     {
  //       roles: [
  //         "system_administrator",
  //         "superadmin",
  //         "general_user",
  //         "data_entry_operator",
  //         "state_data_creator",
  //         "district_data_creator",
  //         "state_data_approver",
  //         "district_data_approver",
  //         "cmo",
  //         "cso",
  //         "development_commissioner",
  //       ],
  //       icon: "iconsminds-big-data",
  //       label: "Raw Data Entry",
  //       to: "/app/protype/addscore/",
  //     },
  //     {
  //       roles: [
  //         "system_administrator",
  //         "superadmin",
  //         "general_user",
  //         "data_entry_operator",
  //         "state_data_creator",
  //         "district_data_creator",
  //         "state_data_approver",
  //         "district_data_approver",
  //         "cmo",
  //         "cso",
  //         "development_commissioner",
  //       ],
  //       icon: "iconsminds-big-data",
  //       label: "Indicator",
  //       to: "/app/protype/addindicatorvalue/",
  //     //  to: "/app/protype/indicator/",
  //     },
      
      
  //   ],
  // },
  {
    roles: [
      "system_administrator",
      "superadmin",
      "data_entry_operator",
      "state_data_creator",
      "district_data_creator",
      "state_data_approver",
      "district_data_approver",
    ],
    id: "newdataentry",
    icon: "iconsminds-big-data",
    label: "Data Upload",
    to: "/app/newdata/",
    subs: [
      {
        roles: ["system_administrator", "superadmin", "data_entry_operator"],
        icon: "iconsminds-big-data",
        label: "Data Entry",
        to: "/app/newdata/addscore/",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "state_data_creator",
          "district_data_creator",
        ],
        icon: "iconsminds-big-data",
        label: "Raw Data Entry",
        to: "/app/newdata/addnewscore/",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "state_data_approver",
          "district_data_approver",
        ],
        icon: "iconsminds-big-data",
        label: "Approve Data",
        to: "/app/newdata/approve/",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "state_data_creator",
          "district_data_creator",
          "state_data_approver",
          "district_data_approver",
        ],
        icon: "iconsminds-big-data",
        label: "Data Status",
        to: "/app/newdata/scorestatus/",
      },
      // {
      //   roles: ["system_administrator", "superadmin", "data_entry_operator"],
      //   icon: "iconsminds-big-data",
      //   label: "Upload Data",
      //   to: "/app/newdata/upload/",
      // },
      {
        roles: ["system_administrator", "superadmin", "data_entry_operator"],
        icon: "iconsminds-big-data",
        label: "District Ranks",
        to: "/app/districtrank",
      },
    ],
  },
  {
    roles: [
      "system_administrator",
      "superadmin",
      "data_entry_operator",
      "general_user",
      "cmo",
      "cso",
      "development_commissioner",
    ],
    id: "targets",
    icon: "iconsminds-target",
    label: "Modify Target Values",
    to: "/app/targets/",
  },
  {
    roles: [
      "system_administrator",
      "superadmin",
      "data_entry_operator",
      "general_user",
      "cmo",
      "cso",
      "development_commissioner",
    ],
    id: "scores",
    icon: "iconsminds-coins-2",
    label: "Scores",
    to: "/app/score/",
    subs: [
      {
        roles: [
          "system_administrator",
          "superadmin",
          // "data_entry_operator",
          // "general_user",
          // "cmo",
          // "cso",
          // "development_commissioner",
        ],
        icon: "iconsminds-big-data",
        label: "National Score",
        to: "/app/score/national/",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          // "data_entry_operator",
          // "general_user",
          // "cmo",
          // "cso",
          // "development_commissioner",
        ],
        icon: "iconsminds-big-data",
        label: "State Score",
        to: "/app/score/state/",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "data_entry_operator",
          "general_user",
          "cmo",
          "cso",
          "development_commissioner",
        ],
        icon: "iconsminds-big-data",
        label: "District Score",
        to: "/app/score/dif/",
      },
    ],
  },
  // {
  //   roles: [
  //     "system_administrator",
  //     "superadmin",
  //     "general_user",
  //     "data_entry_operator",
  //     "state_data_creator",
  //     "district_data_creator",
  //     "state_data_approver",
  //     "district_data_approver",
  //     "cmo",
  //     "cso",
  //     "development_commissioner",
  //   ],
  //   id: "SDGNER",
  //   icon: "iconsminds-dashboard",
  //   label: "Nagaland SDG",
  //   to: "/app/nersdg",
  // },
  {
    roles: [
      "system_administrator",
      "superadmin",
      "data_entry_operator",
      "general_user",
      // "state_data_creator",
      // "district_data_creator",
      // "state_data_approver",
      // "district_data_approver",
      "cmo",
      "cso",
      "development_commissioner",
    ],
    icon: "iconsminds-check",
    id: "reports",
    label: "Reports",
    to: "/app/report/",
    subs: [
      // {
      //   roles: ["all"],
      //   id: "departments",
      //   icon: "iconsminds-profile",
      //   label: "Get Reports",
      //   to: "/app/report/get",
      // },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "Department Schemes",
        to: "/app/report/deptscheme",
      },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "5 Performing Districts",
        to: "/app/report/performing/district",
      },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "5 Critical Districts",
        to: "/app/report/critical/district",
      },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "Top Indicators",
        to: "/app/report/performing/indicator",
      },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "Critical Indicators",
        to: "/app/report/critical/indicator",
      },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "Top Indicators(District)",
        to: "/app/report/performing/districtindicator",
      },
      {
        roles: ["all"],
        id: "departments",
        icon: "iconsminds-profile",
        label: "Critical Indicators(District)",
        to: "/app/report/critical/districtindicator",
      },
      {
        roles: ["all"],
        id: "aspirant",
        icon: "iconsminds-profile",
        label: "Aspirant Indicators",
        to: "/app/report/aspirant",
      },
      {
        roles: ["all"],
        id: "aspirant",
        icon: "iconsminds-profile",
        label: "Performer Indicators",
        to: "/app/report/performer",
      },

      {
        roles: ["all"],
        id: "aspirant",
        icon: "iconsminds-profile",
        label: "Front Runner Indicators",
        to: "/app/report/frontrunner",
      },
      {
        roles: ["all"],
        id: "aspirant",
        icon: "iconsminds-profile",
        label: "Achiever Indicators",
        to: "/app/report/achiever",
      },
      {
        roles: ["all"],
        id: "aspirant",
        icon: "iconsminds-profile",
        label: "No Target Indicators",
        to: "/app/report/notarget",
      },
    ],
  },
  {
    roles: [
      "system_administrator",
      "superadmin",
      "data_entry_operator",
      "general_user",
    ],
    id: "departments",
    icon: "iconsminds-profile",
    label: "FAQs",
    to: "/app/faqs/",
  },
  {
    roles: [
      "system_administrator",
      "superadmin",
      "data_entry_operator",
      "general_user",
      "state_data_creator",
      "district_data_creator",
      "state_data_approver",
      "district_data_approver",
      "cmo",
      "cso",
      "development_commissioner",
    ],
    id: "settings",
    icon: "iconsminds-security-settings",
    label: "Settings",
    to: "/app/blank-page",
    subs: [
      {
        roles: [
          "system_administrator",
          "superadmin",
          "data_entry_operator",
          "general_user",
          "state_data_creator",
          "district_data_creator",
          "state_data_approver",
          "district_data_approver",
          "cmo",
          "cso",
          "development_commissioner",
        ],
        icon: "iconsminds-male-2",
        label: "User Profile",
        to: "/app/userprofile",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "data_entry_operator",
          "general_user",
          "cmo",
          "cso",
          "development_commissioner",
        ],
        icon: "iconsminds-building",
        label: "Departments",
        to: "/app/department",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "data_entry_operator",
          "general_user",
          // "state_data_creator",
          // "district_data_creator",
          // "state_data_approver",
          // "district_data_approver",
          "cmo",
          "cso",
          "development_commissioner",
        ],
        icon: "iconsminds-check",
        label: "Indicators Master",
        to: "/app/indicators/",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "data_entry_operator",
          "general_user",
          // "state_data_creator",
          // "district_data_creator",
          // "state_data_approver",
          // "district_data_approver",
          "cmo",
          "cso",
          "development_commissioner",
        ],
        icon: "iconsminds-check",
        label: "Goals Master",
        to: "/app/goalsmaster/",
      },
      {
        roles: ["system_administrator", "superadmin", "data_entry_operator"],
        icon: "iconsminds-timer",
        label: "Periodicity",
        to: "/app/periodicity",
      },
      {
        roles: ["system_administrator", "superadmin", "data_entry_operator"],
        icon: "iconsminds-profile",
        label: "Unit",
        to: "/app/unit",
      },
      {
        roles: [
          "system_administrator",
          "superadmin",
          "data_entry_operator",
          "general_user",
          "cmo",
          "cso",
          "development_commissioner",
        ],
        icon: "iconsminds-profile",
        label: "Schemes",
        to: "/app/scheme",
      },
      // {
      //   roles: ["system_administrator", "superadmin", "data_entry_operator"],
      //   icon: "iconsminds-location-2",
      //   label: "Location",
      //   to: "/app/location",
      // },
      {
        roles: ["system_administrator", "superadmin", "data_entry_operator"],
        icon: "iconsminds-location-2",
        label: "Districts",
        to: "/app/district",
      },
      {
        roles: ["system_administrator", "superadmin", "data_entry_operator"],
        icon: "iconsminds-location-2",
        label: "States",
        to: "/app/state",
      },
      {
        roles: ["superadmin", "system_administrator"],
        icon: "iconsminds-male-2",
        label: "User Management",
        to: "/app/usermanagement",
      },
    ],
  },
];
export default data;
