# Generated by Django 3.2.12 on 2023-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_otp_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
